export default [
    {
        "DonationId": 3,
        "DonorId": 1,
        "Title": "Slightly used winter clothes",
        "Quantity": 3,
        "Weight": 1.50,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-03-18T05:02:00",
        "PostedDate": null,
        "Description": "Donating winter clothes for needy person <br />size: Small<br />Condition:8/10",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "pending",
        "IsActive": true,
        "PostedDate": '23 March 2022',
        "Image1base64": 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmVhdXRpZnVsJTIwY2F0fGVufDB8fDB8fA%3D%3D&w=1000&q=80',
        "Image2base64": 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmVhdXRpZnVsJTIwY2F0fGVufDB8fDB8fA%3D%3D&w=1000&q=80'
    },
    {
        "DonationId": 8,
        "DonorId": 1,
        "Title": "3 Science books",
        "Quantity": 1,
        "Weight": 1.00,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-03-20T12:20:00",
        "PostedDate": null,
        "Description": "sadasadsasd",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "approve",
        "IsActive": true,
        "PostedDate": '23 March 2022'
    },
    {
        "DonationId": 9,
        "DonorId": 1,
        "Title": "Warm Gloves",
        "Quantity": 1,
        "Weight": 0.30,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-03-20T14:12:00",
        "PostedDate": null,
        "Description": "sasdsdasdasad",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "reject",
        "IsActive": false,
        "PostedDate": '23 March 2022'
    },
    {
        "DonationId": 1003,
        "DonorId": 1,
        "Title": "SchoOL Uniform",
        "Quantity": 1,
        "Weight": 0.30,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-04-03T11:42:00",
        "PostedDate": null,
        "Description": "asdassdadasjksdlakjsdalkj",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "reject",
        "IsActive": true,
        "PostedDate": '23 March 2022'
    },
    {
        "DonationId": 1004,
        "DonorId": 1,
        "Title": "sss",
        "Quantity": 1,
        "Weight": 0.50,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-04-03T12:25:00",
        "PostedDate": null,
        "Description": "asdasdas",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "reject",
        "IsActive": false,
        "PostedDate": '23 March 2022'
    },
    {
        "DonationId": 1005,
        "DonorId": 1,
        "Title": "asdsads",
        "Quantity": 1,
        "Weight": 2.00,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-04-03T12:40:00",
        "PostedDate": null,
        "Description": "zxzxxzxz",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "reject",
        "IsActive": false,
        "PostedDate": '23 March 2022'
    },
    {
        "DonationId": 1006,
        "DonorId": 1,
        "Title": "asdsads",
        "Quantity": 1,
        "Weight": 2.00,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-04-03T12:40:00",
        "PostedDate": null,
        "Description": "zxzxxzxz",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "reject",
        "IsActive": false,
        "PostedDate": '23 March 2022'
    },
    {
        "DonationId": 1007,
        "DonorId": 1,
        "Title": "asdsads",
        "Quantity": 1,
        "Weight": 2.00,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-04-03T12:40:00",
        "PostedDate": null,
        "Description": "zxzxxzxz",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "reject",
        "IsActive": true,
        "PostedDate": '23 March 2022'
    },
    {
        "DonationId": 1008,
        "DonorId": 1,
        "Title": "asdsads",
        "Quantity": 1,
        "Weight": 2.00,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-04-03T12:40:00",
        "PostedDate": null,
        "Description": "zxzxxzxz",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "reject",
        "IsActive": false,
        "PostedDate": '23 March 2022'
    },
    {
        "DonationId": 1009,
        "DonorId": 1,
        "Title": "asdsads",
        "Quantity": 1,
        "Weight": 2.00,
        "QuantityPerUnit": 1,
        "ExpiryDate": "2022-04-03T12:40:00",
        "PostedDate": null,
        "Description": "zxzxxzxz",
        "Rating": 0,
        "Condition": "Used",
        "Category": "Clothes",
        "LocationCo": 0,
        "Image1base64": null,
        "Image2base64": null,
        "Image3base64": null,
        "Image1Name": null,
        "Image2Name": null,
        "Image3Name": null,
        "Status": "reject",
        "IsActive": false,
        "PostedDate": '23 March 2022'
    }
]